spring.application.name=lektion-4-uppgifter

# --- R2DBC (reactive driver) (reactive driver, async / non-blocking)
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/EnterpriseEclipse
spring.r2dbc.username=postgres
spring.r2dbc.password=anna12345

# --- Flyway (JDBC driver), doesn't know about R2DBC ahead of time
spring.flyway.url=jdbc:postgresql://localhost:5432/EnterpriseEclipse
spring.flyway.user=postgres
spring.flyway.password=anna12345

# Flyway directory path to db.migration
spring.flyway.locations=classpath:db/migration